# Generated by Django 3.1.7 on 2021-05-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210510_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
