# Generated by Django 3.1.7 on 2021-05-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210510_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
