# Generated by Django 3.1.7 on 2021-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210511_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='issue_period',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
