# Generated by Django 3.1.7 on 2021-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='issue_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
