# Generated by Django 3.1.7 on 2021-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20210514_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Abstract'), (2, 'Business'), (3, 'Philosophy'), (4, 'Psychology'), (5, 'Science'), (6, 'Science Fiction')], default=1),
        ),
    ]
