# Generated by Django 3.1.7 on 2021-05-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20210514_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
