# Generated by Django 3.1.7 on 2021-05-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_auto_20210514_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
